repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^(data|patches)/.*$
      - id: end-of-file-fixer
        exclude: ^(data|patches)/.*$
      - id: check-yaml
        exclude: ^data/

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        name: Fix *.c,*.cc,*.cpp,*.h,*.hpp
        entry: clang-format
        language: system
        files: ^(src|python|tests|examples)/.*\.(c|cc|cpp|h|hpp)$
        args: ["-i", "-style=Google"]
